### ISSUE TITLE
Check for map function everynwhere in the codebase for the null condition

### ISSUE THREAD

**Issue by ahmad-rameez** [rav291/CSGO_NATION#2]
![image](https://user-images.githubusercontent.com/24876047/96995078-3fad8900-154b-11eb-90b0-543ac6fc12c4.png)

The above error is on ranking page.

**Comment by rav291** [comment]
Added **thead** and **tbody**, since **tr** cannot be the direct child of table element. 
Thanks for pointing out.

**Comment by rav291** [comment]
Issue resolved
